### PR TITLE
Checking linters

### PR DESCRIPTION
**Pull request by AlejandraKeber**
Hello guys
Thanks for being my PR reviewers.

In this project set-up I am including:
- Created a feature branch
- Added linterns
- Added HTML and CSS files to the feature branch
- Added .and updated gitignore file
- Updated Readme file
- Checked lintern errors
- Updated de PR description

I hope I included all your suggestions and thanks again for reviewing my PR

### CODE REVIEW

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @AlejandraKeber , :wave:
### I'm Levy, your PR reviewer

Excellent work :sunglasses: :  you've done
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights :muscle: 
- Good job for using the correct git-flow :heavy_check_mark: 
- All linters are passing :heavy_check_mark: 
- Good commit messages :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly make sure to add a good PR title and PR description. It makes your repo looks more professional. :wink: 

   - Example of good PR
image

- [ ] Kindly make sure to add `test.md` file in the `gitignore` file in order to be pushed to our Github repo as requested in the project's requirement. :wink: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly consider the microverse README [template](https://github.com/microverseinc/readme-template) and try to customize it personally which will lead your repo to look more professional :sunglasses: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AlejandraKeber** [comment]
Hello @levy002 
Thanks for reviewing my PR
I think I included the required changes so I send my PR again
In this PR:
- Included the .md file into the .gitignore file

Thanks for reviewing my PR!!!

**Review by frank1738 — CHANGES_REQUESTED** [review]
Hi @AlejandraKeber , I'm @frank1738 your Code Reviewer

Good job implementing some of the changes requested by the previous reviewer but there are some issues that you still need to work on to go to the next project but you are almost there!

almost there

## Highlights
- No linter errors ✔️ 
- Good job for using the correct git-flow✔️ 
- Descriptive Comments ✔️ 

## Required Changes ♻️
- [ ] as the previous reviewer requested, would you please add a description to your pull request describing what you did. This is important for documentation purposes.
### Here is an example of a descriptive Pull Request

image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Instead of naming your branch `FeatureBranch` , you can consider  giving it a descriptive name like `Project-Setup`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by awais-amjed — APPROVED** [review]
Hi @AlejandraKeber , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Great Job on implementing all the required changes 🥳 Congratulations! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

gif

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
